name: Run Discord Bot (6h loop)

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TOKEN1: ${{ secrets.TOKEN1 }}
      TOKEN2: ${{ secrets.TOKEN2 }}
      CH_IDS: ${{ secrets.CH_IDS }}
      WEBHOOK1: ${{ secrets.WEBHOOK1 }}
      WEBHOOK2: ${{ secrets.WEBHOOK2 }}
      # DEFAULT_PRESENCE: ${{ secrets.DEFAULT_PRESENCE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate config/config.json from secrets
        run: |
          mkdir -p config
          cat <<EOF > config/config.json
          {
            "tokens": ["${TOKEN1}", "${TOKEN2}"],
            "CH_IDS": ${CH_IDS},
            "owo_ID": "408785106942164992",
            "reaction_ID": "519287796549156864",
            "webhookUrls": ["${WEBHOOK1}", "${WEBHOOK2}"],
            "DEFAULT_PRESENCE": "invisible"
          }
          EOF

      - name: Run bot for 6 hours
        run: |
          node launcher.js &
          BOT_PID=$!
          sleep 21600  # 6 saat
          kill $BOT_PID || true

      - name: Trigger next run
        run: |
          gh workflow run "Run Discord Bot (6h loop)" --ref ${{ github.ref_name }}
        env:
          # PAT_TOKEN is the secret containing your Personal Access Token
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
