name: Run Discord Bot (Loop)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # her 6 saatte bir (00:00, 06:00, 12:00, 18:00)

concurrency:
  group: discord-bot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TOKEN1: ${{ secrets.TOKEN1 }}
      TOKEN2: ${{ secrets.TOKEN2 }}
      CH_IDS: ${{ secrets.CH_IDS }}
      WEBHOOKS: ${{ secrets.WEBHOOKS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --only=production

      - name: Convert secrets into JSON arrays
        run: |
          CH_JSON=$(echo "$CH_IDS" | sed 's/, */","/g' | sed 's/^/["/' | sed 's/$/"]/')
          echo "CH_JSON=$CH_JSON" >> $GITHUB_ENV

      - name: Run bot (max 6h)
        run: |
          timeout 6h node launcher.js
